/*
===============================================================================
Category Distribution Analysis
===============================================================================
Objective:
    - Aggregate data to understand how values are distributed across different 
      segments.
    - Identify patterns in players, tournaments, and match performance.
Techniques Used:
    - Aggregation (SUM, COUNT, AVG)
    - GROUP BY and ORDER BY
Summary:
    The following queries explore key dimensions such as player demographics,
    tournament categories, and match performance to uncover meaningful insights.
===============================================================================
*/

-- Find total players by country
SELECT
    country,
    COUNT(player_key) AS total_players
FROM esports.dim_players
GROUP BY country
ORDER BY total_players DESC;

-- Find total players by region
SELECT
    region,
    COUNT(player_key) AS total_players
FROM esports.dim_players
GROUP BY region
ORDER BY total_players DESC;

-- Find total players by game title
SELECT
    game_title,
    COUNT(player_key) AS total_players
FROM esports.dim_players
GROUP BY game_title
ORDER BY total_players DESC;

-- Find total players by role across all game titles
SELECT
    game_title,
    role,
    COUNT(player_key) AS total_players
FROM esports.dim_players
GROUP BY game_title, role
ORDER BY game_title, total_players DESC;

-- Find total players by status (Active, Inactive, Retired)
SELECT
    status,
    COUNT(player_key) AS total_players
FROM esports.dim_players
GROUP BY status
ORDER BY total_players DESC;

-- What is the average annual salary per game title?
SELECT
    game_title,
    AVG(annual_salary_usd) AS avg_salary
FROM esports.dim_players
GROUP BY game_title
ORDER BY avg_salary DESC;

-- What is the average annual salary per region?
SELECT
    region,
    AVG(annual_salary_usd) AS avg_salary
FROM esports.dim_players
GROUP BY region
ORDER BY avg_salary DESC;

-- Find total tournaments by game title
SELECT
    game_title,
    COUNT(tournament_key) AS total_tournaments
FROM esports.dim_tournaments
GROUP BY game_title
ORDER BY total_tournaments DESC;

-- What is the total prize pool distributed per game title?
SELECT
    game_title,
    SUM(prize_pool_usd) AS total_prize_pool
FROM esports.dim_tournaments
GROUP BY game_title
ORDER BY total_prize_pool DESC;

-- What is the average prize pool per tournament format?
SELECT
    format,
    AVG(prize_pool_usd) AS avg_prize_pool
FROM esports.dim_tournaments
GROUP BY format
ORDER BY avg_prize_pool DESC;

-- What is the total prize pool distributed per region?
SELECT
    region,
    SUM(prize_pool_usd) AS total_prize_pool
FROM esports.dim_tournaments
GROUP BY region
ORDER BY total_prize_pool DESC;

-- What is the total kills generated by each player?
SELECT
    p.player_key,
    p.gamertag,
    p.game_title,
    SUM(f.kills) AS total_kills
FROM esports.fact_matchstats f
LEFT JOIN esports.dim_players p
    ON p.player_key = f.player_key
GROUP BY
    p.player_key,
    p.gamertag,
    p.game_title
ORDER BY total_kills DESC;

-- What is the average KDA ratio per game title?
SELECT
    p.game_title,
    AVG(f.kda_ratio) AS avg_kda
FROM esports.fact_matchstats f
LEFT JOIN esports.dim_players p
    ON p.player_key = f.player_key
GROUP BY p.game_title
ORDER BY avg_kda DESC;

-- What is the distribution of match outcomes across all maps?
SELECT
    map_played,
    match_outcome,
    COUNT(*) AS total_matches
FROM esports.fact_matchstats
GROUP BY map_played, match_outcome
ORDER BY map_played, total_matches DESC;

-- What is the total damage dealt by players per region?
SELECT
    p.region,
    SUM(f.damage_dealt) AS total_damage
FROM esports.fact_matchstats f
LEFT JOIN esports.dim_players p
    ON p.player_key = f.player_key
GROUP BY p.region
ORDER BY total_damage DESC;
